<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="stirling.software.common.service.JobExecutorServiceTest" tests="6" skipped="0" failures="0" errors="0" timestamp="2025-07-10T21:18:52.788Z" hostname="MacBook-Pro.local" time="0.034">
  <properties/>
  <testcase name="shouldHandleSyncJobError()" classname="stirling.software.common.service.JobExecutorServiceTest" time="0.015"/>
  <testcase name="shouldUseCustomTimeoutWhenProvided()" classname="stirling.software.common.service.JobExecutorServiceTest" time="0.008"/>
  <testcase name="shouldRunSyncJobSuccessfully()" classname="stirling.software.common.service.JobExecutorServiceTest" time="0.002"/>
  <testcase name="shouldRunAsyncJobSuccessfully()" classname="stirling.software.common.service.JobExecutorServiceTest" time="0.003"/>
  <testcase name="shouldQueueJobWhenResourcesLimited()" classname="stirling.software.common.service.JobExecutorServiceTest" time="0.002"/>
  <testcase name="shouldHandleTimeout()" classname="stirling.software.common.service.JobExecutorServiceTest" time="0.003"/>
  <system-out><![CDATA[14:18:52.803 [Test worker] ERROR stirling.software.common.service.JobExecutorService -- Error executing synchronous job: Test error
java.lang.RuntimeException: Test error
	at stirling.software.common.service.JobExecutorServiceTest.lambda$shouldHandleSyncJobError$2(JobExecutorServiceTest.java:117)
	at stirling.software.common.service.JobExecutorService.lambda$runJobGeneric$3(JobExecutorService.java:197)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
